#
# Build simulation environment - Windows
#
parameters:
  poolName: 'windows-2019'
  rgName: 'sandbox-iiot'

jobs:
  - job: Build_windows_environment
    displayName: Build windows environment
    pool:
      vmImage: ${{ parameters.poolName }}
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: 'AzureRmPipeline-conn'
        subscriptionName: '9dd2b4d0-3dad-4aeb-85d8-c3addb78127a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '${{ parameters.rgName }}-windows-rg'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'tools/templates/simulation_windows.json'
        overrideParameters: '-edgeUsername "sandboxuserwin" -edgePassword $(vmPassword)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'ARMOutput'
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'AzureRmPipeline-conn'
        ScriptType: 'FilePath'
        ScriptPath: 'tools/scripts/read-output-params.ps1'
        ScriptArguments: '-armOutputString ''$(ARMOutput)'''
        azurePowerShellVersion: 'LatestVersion'
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'AzureRmPipeline-conn'
        ScriptType: 'FilePath'
        ScriptPath: 'tools/scripts/connect-edge.ps1'
        ScriptArguments: '-ResourceGroupName "$(Output_resourceGroup)" -IoTHubName "$(Output_iothub-name)" -IoTHubConnectionString "$(Output_iothub-connstring)" -SimulationVMName "$(Output_edgeVMName)" -Env "windows"'
        azurePowerShellVersion: 'LatestVersion'